// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ... 
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1gGsTRWCZClCgyv-g8GqNySKQsdyVO8s',
    appId: '1:174390230237:web:6e2f391b8ac7f760e46f34',
    messagingSenderId: '174390230237',
    projectId: 'rentcarapp-d1e3e',
    authDomain: 'rentcarapp-d1e3e.firebaseapp.com',
    storageBucket: 'rentcarapp-d1e3e.firebasestorage.app',
    measurementId: 'G-TX9SPEG1F9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlf8mn9uKEEKpTorjt3JoBNvUQEdHBWzc',
    appId: '1:174390230237:android:8872e318551ce0bae46f34',
    messagingSenderId: '174390230237',
    projectId: 'rentcarapp-d1e3e',
    storageBucket: 'rentcarapp-d1e3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdW-R91WWFdcfwIA4Ha42s89dcBiKShRY',
    appId: '1:174390230237:ios:fae777d54cfd3257e46f34',
    messagingSenderId: '174390230237',
    projectId: 'rentcarapp-d1e3e',
    storageBucket: 'rentcarapp-d1e3e.firebasestorage.app',
    iosBundleId: 'com.example.rentcarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdW-R91WWFdcfwIA4Ha42s89dcBiKShRY',
    appId: '1:174390230237:ios:fae777d54cfd3257e46f34',
    messagingSenderId: '174390230237',
    projectId: 'rentcarapp-d1e3e',
    storageBucket: 'rentcarapp-d1e3e.firebasestorage.app',
    iosBundleId: 'com.example.rentcarApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1gGsTRWCZClCgyv-g8GqNySKQsdyVO8s',
    appId: '1:174390230237:web:06051a2998edecc7e46f34',
    messagingSenderId: '174390230237',
    projectId: 'rentcarapp-d1e3e',
    authDomain: 'rentcarapp-d1e3e.firebaseapp.com',
    storageBucket: 'rentcarapp-d1e3e.firebasestorage.app',
    measurementId: 'G-7XWZN3Y26Z',
  );

}